name = "amazon-video-api"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# 开发环境变量
[env.development]
vars = { ENVIRONMENT = "development" }

# 生产环境变量
[env.production]
vars = { ENVIRONMENT = "production" }

# KV 命名空间（如果需要存储数据）
kv_namespaces = [
  { binding = "VIDEO_STORE", id = "你的KV命名空间ID" }
]

[vars]
ENVIRONMENT = "development" 